# Dynmap-Towny configuration
#
update:
  # Seconds between checks for Residence updates
  period: 300

layer:
  name: "Towny"
  # Make mobs layer hidden by default
  hidebydefault: false
  # ordering priority in layer menu (low goes before high - default is 0)
  layerprio: 2
  # (optional) set minimum zoom level before layer is visible (0 = defalt, always visible)
  minzoom: 0
  # Show shop blocks with their own fill color
  showShops: false
  # Show arena blocks with their own fill color
  showArenas: false
  # Show embassy blocks with their own fill color
  showEmbassies: false
  # Show wild blocks with their own fill color
  showWilds: false

# Allow all residents of a given town to see one another, when player info is protected in dynmap
visibility-by-town: true
# Allow all residents of a given nation to see one another, when player info is protected in dynmap
visibility-by-nation: true

# Use dynamic nation colors, which are set in-game by individual nations (using /n set mapcolor <color>)
dynamic-nation-colors: true

# Format for popup - substitute values for macros
infowindow: '<div class="infowindow"><span style="font-size:120%;">%regionname% (%nation%)</span><br /> Mayor <span style="font-weight:bold;">%playerowners%</span><br /> Associates <span style="font-weight:bold;">%playermanagers%</span><br/>Flags<br /><span style="font-weight:bold;">%flags%</span></div>'

regionstyle:
  strokeColor: "#FF0000"
  strokeOpacity: 0.8
  strokeWeight: 3
  fillColor: "#FF0000"
  fillOpacity: 0.35
  homeicon: "blueflag"
  capitalicon: "king"
  fillColorShops: "#0000FF"
  fillColorArenas: "#FF00FF"
  fillColorEmbassies: "#00FFFF"
  fillColorWilds: "#00FF00"
  boost: false
  
# Optional setting to limit which regions to show, by name - if commented out, all regions are shown
# To show all regions on a given world, add 'world:<worldname>' to the list
visibleregions: []
  
# Optional setting to hide specific regions, by name
# To hide all regions on a given world, add 'world:<worldname>' to the list
hiddenregions: []
  
# Optional per-region overrides for regionstyle (any defined replace those in regionstyle)
custstyle:
  customregion1:
    strokeColor: "#00FF00"
    y: 64
  customregion2:
    strokeColor: "#007F00"
    y: 64
    boost: false

# Optional per-nation overrides (custstyle has priority over nationstyle),  _none_ is used for towns with no nation
nationstyle:  
  NationOfBlue:
    strokeColor: "#0000FF"
    fillColor: "#0000FF"
    boost: false
  _none_:
    homeicon: "greenflag"
    
# Chat settings for use with TownyChat
chat:
  sendlogin: true
  sendquit: true
  format: "&color;2[WEB] %playername%: &color;f%message%"
