# Dynmap-Towny configuration
#
update:
  # Seconds between checks for Residence updates
  period: 300

layer:
  name: "Towny"
  # Make mobs layer hidden by default
  hidebydefault: false
  # ordering priority in layer menu (low goes before high - default is 0)
  layerprio: 2

# Format for popup - substitute values for macros
infowindow: '<div class="infowindow"><span style="font-size:120%;">%regionname% (%nation%)</span><br /> Mayor <span style="font-weight:bold;">%playerowners%</span><br /> Associates <span style="font-weight:bold;">%playermanagers%</span><br/>Flags<br /><span style="font-weight:bold;">%flags%</span></div>'

regionstyle:
  strokeColor: "#FF0000"
  strokeOpacity: 0.8
  strokeWeight: 3
  fillColor: "#FF0000"
  fillOpacity: 0.35
  homeicon: "blueflag"
  capitalicon: "king"
  
# Optional setting to limit which regions to show, by name - if commented out, all regions are shown
visibleregions: []
  
# Optional setting to hide specific regions, by name
hiddenregions: []
  
# Optional per-region overrides for regionstyle (any defined replace those in regionstyle)
custstyle:
  customregion1:
    strokeColor: "#00FF00"
  customregion2.subzone3:
    strokeColor: "#007F00"

# Optional per-nation overrides (custstyle has priority over nationstyle),  _none_ is used for towns with no nation
nationstyle:  
  NationOfBlue:
    strokeColor: "#0000FF"
    fillColor: "#0000FF"
  _none_:
    homeicon: "greenflag"
    
